# Generated by Django 5.2.3 on 2025-06-23 03:54

from django.db import migrations, models
def fix_default_images(apps, schema_editor):
    Profile = apps.get_model('blog', 'Profile')
    for profile in Profile.objects.filter(image='default.jpg'):
        profile.image = 'profile_pics/default.jpg'
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
